import os
import copy
import numpy as np
from src.bo_manager import BOmanager as BO


def apply_BO(beehive, index, role):
    """
    Applies Bayesian Optimization (BO) to refine the solution of a specific bee.

    Parameters:
        :param Beehive beehive : the Beehive class instance
        :param int index       : index of the bee in the population
        :param str role        : the current role of the bee
    """
    dim_num = len(beehive.dataset_obj.columns)
    population_size = len(beehive.population)

    _pbounds = {}
    _decay_bounds = {}

    explore_decay = 1.0
    if dim_num > 0 and population_size > 0 :
        try: 
            explore_decay = pow(population_size, (1 / dim_num))
        except ValueError:
            pass
    
    for idx_col in range(dim_num):
        col_name = beehive.dataset_obj.columns[idx_col]
        current_val = beehive.population[index].vector[idx_col]
        lower_bound = beehive.lower[idx_col]
        upper_bound = beehive.upper[idx_col]
        
        _interval = upper_bound - lower_bound

        _decay_bounds[col_name] = (max(current_val - _interval / (2 * explore_decay), lower_bound),
                                   min(current_val + _interval / (2 * explore_decay), upper_bound))

        _pbounds[col_name] = (float(lower_bound),
                              float(upper_bound) * 1.0000000001)

    _init_points = np.asarray(beehive.population[index].memory['x'])

    log_dir = os.path.dirname(beehive.path_to_log) if beehive.path_to_log else "."

    BO_model = BO(f=None,
                  dataset=beehive.dataset_obj.filename,
                  x_columns=beehive.dataset_obj.columns,
                  target_column=beehive.dataset_obj.target_column,
                  constraint_column=beehive.dataset_obj.constraint_column,
                  constraints_bounds=[(0, beehive.dataset_obj.constraint_value)],
                  seed=beehive.seed,
                  output_path=log_dir,
                  init_points=_init_points,
                  #n_iter=min(beehive.BO_steps, beehive.max_itrs - beehive.iter),
                  n_iter=1,
                  log_name=f'BO_Bee_{index}_iter_{beehive.iter}_{role}',
                  decay_bounds=_decay_bounds)

    for idx_pt in range(len(BO_model.points)):

        beehive.population[index].BO_memory.append([
            BO_model.points[idx_pt],
            float(BO_model.target[idx_pt]),
            float(BO_model.constr[idx_pt])
        ])

    execution_time = store_BO_data(beehive, index)

    return execution_time


def store_BO_data(beehive, index):
    """
    Processes a solution candidate generated by Bayesian Optimization (BO) from the bee's BO_memory.

    Parameters:
        :param Beehive beehive  : the Beehive class instance
        :param int index        : index of the bee in the population
    """
    BO_value = beehive.population[index].BO_memory.popleft()
    beehive.population[index].BO_to_do -= 1
    beehive.mutated_population[index] = copy.deepcopy(beehive.population[index])

    beehive.mutated_population[index].vector[:] = BO_value[0]
    beehive.mutated_population[index].value = BO_value[1]
    beehive.mutated_population[index].constraint = BO_value[2]

    beehive.mutated_population[index]._fitness()

    beehive.mutated_population[index].role = 'Worker_BO'
    beehive.mutated_population[index].counter_idx = index

    if not beehive._async:
        beehive.update_bee_status(index)

    if beehive.memory_type == 'global':
        beehive.global_mem.append(beehive.mutated_population[index].vector[:])

    if beehive.use_cache and (beehive.mutated_population[index].vector.tobytes() in beehive.cache):
        return 0.0

    return beehive.dataset_obj.get_execution_time(beehive.mutated_population[index].vector)